### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by demyxco** [carry0987/Imgur-Upload#2]
Hi, I'm using your repo for my plugin used in an open source community, called [Elgg](https://elgg.org/plugins/2033439). 

I've modified this part so I can initialize multiple Imgur classes via its options.
https://github.com/carry0987/Imgur-Upload/blob/c828b310c3c106d7af055d1fb66559f3fe16d446/js/imgur.js#L29

Modifications here: https://github.com/demyxco/elgg/blob/b3e7537466b0e2797e932ac8d8b7324b69e1c10c/plugins/imgur/views/default/imgur.js#L30-L32

Modifications in action can seen here from another of my plugin:
https://github.com/demyxco/elgg/blob/b3e7537466b0e2797e932ac8d8b7324b69e1c10c/plugins/blogcoverphoto/views/default/js/blogcoverphoto/blogcoverphoto.js#L20-L26

Btw, thanks for the great plugin!

**Comment by carry0987** [comment]
Thanks a lot !! @demyxco
